### ISSUE TITLE
by enhancing the axial resolution

### ISSUE THREAD

**Issue by 464hee** [cxm12/UNiFMIR#2]
In the description at the end of the fourth page of the paper's PDF,Thesis Description:
The proposed UniFMIR method could offer near-isotropic imaging by enhancing the axial resolution, 
issues:
When I execute mainiso.py, the example data Isotropic/Liver.tif
inputs the size (301, 752, 752), the output is still (301, 752, 752)
Is there anything else that needs to be done to this output file?
@ryanhe312 @cxm12

**Comment by cxm12** [comment]
Nothing. You can compare the XY (or XZ) slices between the original image and the processed image. The axial resolution of the input data has already been upscaled.

**Comment by 464hee** [comment]
ok
